on: push

name: Jest Suite

jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - run: yarn install --ignore-optional --frozen-lockfile --non-interactive --check-files

      - run: yarn build

      - run: yarn jest:ci
